name: Publish
on:
  release:
    types: [released, prereleased]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 1.0.0-alpha01)"
        required: true
        default: "1.0.0-alpha01"
        type: string
      dry_run:
        description: "Dry run (test without publishing)"
        required: false
        default: false
        type: boolean
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Set version from input
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Setting version to ${{ github.event.inputs.version }}"
          sed -i '' 's/version = ".*"/version = "${{ github.event.inputs.version }}"/' library/build.gradle.kts

      - name: Build library
        run: ./gradlew :library:build --no-configuration-cache

      - name: Dry run - Show what would be published
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "=== DRY RUN - No actual publishing ==="
          echo "Version: ${{ github.event.inputs.version || 'from release tag' }}"
          echo "Library artifacts would be published to Maven Central"
          ./gradlew :library:tasks --group=publishing

      - name: Publish to MavenCentral
        if: github.event.inputs.dry_run != 'true'
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
          # ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
